### PR TITLE
[ENV] Add support for passing the coveralls token via an env var

### PR DESCRIPTION
**Pull request by orta**
Note: this happens to me locally too, https://github.com/venmo/slather/issues/74
Re: https://github.com/venmo/slather/issues/68 - I've added support for using an ENV var to pass your token in. Called it Coverage so that it can fit the other providers too.

### CODE REVIEW

**Comment by marklarr** [comment]
Can we change it to `CI_ACCESS_TOKEN`? `COVERAGE_ACCESS_TOKEN` I would expect to be the token for Coveralls if you have Coveralls Pro. This token is the token for travis/circle ci when you have their pro.

**Comment by orta** [comment]
I thought that originally, but the token is the coveralls token as opposed to the one for the CI. Calling it the CI_ACCESS_TOKEN implies that would you find it at travis/circle when you have to get it from coveralls. 

Happy to switch though, I have no horse in this race.

**Comment by marklarr** [comment]
Oh, you're right, I just looked back at https://github.com/venmo/slather/pull/17. That is the token that comes from Coveralls, not Travis. can you change the other variables to `coverage_access_token`, in that case, for consistency? :grin:

**Comment by orta** [comment]
done :+1:

**Comment by marklarr** [comment]
Sweet, thanks orta!

**Comment by orta** [comment]
@chrismaddern - this probably breaks your current install ^

**Comment by marklarr** [comment]
I'll have to do a minor version update. Hopefully this doesn't affect too
many ppl.

**Pull request merged**
