### PR TITLE
Copy files to the html directory so it can all be zipped up

### PR DESCRIPTION
**Pull request by joshrlesch**

### CODE REVIEW

**Comment by colincornaby** [comment]
Hey, just saw this. Any reason this got closed? I'm having this exact issue.

**Comment by joshrlesch** [comment]
Ha well I didn't mean to open it actually. It was suppose to open in my fork but defaults to the original repo and I clicked to fast oops. I can look into actually opening one if it would be beneficial.

**Comment by colincornaby** [comment]
I think this would be worthwhile. I'm just looking at adopting Slather, but the HTML reports are not portable, so if I upload them to a web server or to our CI server they're totally broken. This pull request looks like it solves that. Hard to believe they were intentionally coded that way.

**Comment by joshrlesch** [comment]
It works for us, but we use teamcity. So I just forked it and made multiple changes including being able to upload to coveralls.

**Comment by colincornaby** [comment]
Thanks, I tried out your fork, but it has issues marking uncovered lines as covered. I went ahead and opened an issue in this project.

**Comment by joshrlesch** [comment]
Yeah I don't do anything other than just copy pasting the css/js files on the generation of the html directory. So that bug is most likely part of slather itself.

**Comment by colincornaby** [comment]
I actually wasn't seeing the issue in mainline Slather. I created my own fork to bring your patch together with the current head of master. I'll check it over and then open a pull request for my issue if it all works.

**Pull request closed without merging**
