### PR TITLE
Update dependencies for cocoa pods 0.39.0

### PR DESCRIPTION
**Pull request by tarbrain**
Squashed commit of the following:

commit d1950245e90660229a303bba8d4ed7674b964d44
Author: Julian Krumow <julian.krumow@artcom.de>
Date:   Mon Oct 12 10:27:36 2015 +0200

    Update dependencies.

commit bef60c020758ec269f96de0bbf5a0d25b8638fbd
Author: Julian Krumow <julian.krumow@tarbrain.com>
Date:   Mon Oct 12 10:25:51 2015 +0200

    Update slather.gemspec

commit eda2757c390d43b81254d4c5c13fc8bc07bd1d9c
Author: Julian Krumow <julian.krumow@tarbrain.com>
Date:   Tue Sep 29 23:20:21 2015 +0200

    test_xcode_7

commit 2d2a01d75e1426c7a3957085ee00e62a201fbe72
Merge: fcb4efb 2f57921
Author: Julian Krumow <julian.krumow@tarbrain.com>
Date:   Tue Sep 29 23:19:00 2015 +0200

    Merge remote-tracking branch 'origin/master' into develop

    # Conflicts:
    #	CHANGELOG.md

commit fcb4efb0429ed83cda023794dee759157cd7517b
Author: Julian Krumow <julian.krumow@tarbrain.com>
Date:   Fri Jul 24 23:00:55 2015 +0200

    Update changelog.

    FIxed issue #94

commit 62c4fcd4b5a446835333ebfc019ce89994036004
Author: Julian Krumow <julian.krumow@tarbrain.com>
Date:   Fri Jul 24 22:53:34 2015 +0200

    Changed usage of cocoapods plugin API which has changed in version 0.38.x

commit 0fc3de4bfc776a8e976ef8030b8adad0f7bd66a2
Author: Julian Krumow <julian.krumow@tarbrain.com>
Date:   Fri Jul 24 22:29:00 2015 +0200

    Revert.

commit e898a665f9bdf02a864f23410d00dfe5a89f0d5f
Author: Julian Krumow <julian.krumow@tarbrain.com>
Date:   Fri Jul 24 22:28:24 2015 +0200

    Push.

commit 2ea7b6a82d4ae56ab54d0083d3ba3a6d72e2d236
Author: Julian Krumow <julian.krumow@tarbrain.com>
Date:   Fri Jul 24 22:23:33 2015 +0200

    Update dependencies cocoapods and xcodeproj.

### CODE REVIEW

**Comment by dev4dev** [comment]
is anybody alive?

**Comment by tarbrain** [comment]
Good question. Not much happening here lately.

**Comment by davidrothera** [comment]
Works fine for me :+1: @eliperkins could you take a look and merge?

**Comment by johnboiles** [comment]
:ship: :ship: :ship:

**Comment by tarbrain** [comment]
Hello? Is anybody maintaining this repo?

**Comment by zac** [comment]
I'm currently running into this too...

**Comment by JamieREvans** [comment]
I really need this update. Should we consider using the fork, instead?

**Comment by Xiangxin** [comment]
Can we merge this fix soon ?

**Comment by 3lvis** [comment]
:+1:

**Comment by eliperkins** [comment]
Cleaned up the commit message for clarity in #109. Thanks @tarbrain !

**Pull request closed without merging**
