### PR TITLE
Use SimpleCov to only generate coverage for files in lib/

### PR DESCRIPTION
**Pull request by marklarr**

### CODE REVIEW

**Comment by marklarr** [comment]
I'm hoping this will improve the coverage. It looks like it's been including a bunch of gems in the computation of our test coverage.

**Comment by marklarr** [comment]
simple cob :corn:

**Comment by marklarr** [comment]
Ugh, it's still including all that junk.

**Comment by ayanonagon** [comment]
not-so-simple cob :corn:

**Comment by marklarr** [comment]
Smart Cob :iphone: :corn:

**Pull request closed without merging**
